---

- name: Ensure kernel ip_forward is enabled
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: True
    state: present
    reload: True

- name: Install required packages
  yum:
    state: present
    name: "{{ docker_packages_so }}"

- include_tasks: lvm.yml
  when: docker_lvm_storage_enable

- name: Restore SELinux labeling on docker lib directory
  command: restorecon /var/lib/docker
  when: ansible_mounts|selectattr('mount','equalto','/var/lib/docker/overlay2')|list|length and ansible_facts.selinux.status == 'enabled'

- name: Ensure docker config dirs exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0600
  with_items:
    - /etc/docker
    - /etc/systemd/system/docker.service.d
    - ~/.docker

- name: Configure docker login
  copy: 
    dest: ~/.docker/config.json 
    mode: 0600
    content: "{{ docker_registry.login | to_nice_json }}"

- name: Configure docker daemon
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon_config | to_nice_json }}"
  register: docker_daemon_config_file

- name: Override docker systemd unit configuration
  template:
    src: systemd/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
  register: docker_systemd_override

#- name: Configure systemd docker unit
#  copy:
#    dest: /lib/systemd/system/docker.service
#    src: docker/systemd/docker.service
#  register: docker_systemd_config

- name: Reload docker service
  systemd:
    name: docker
    daemon_reload: True
    state: restarted
  when: docker_daemon_config_file.changed or docker_systemd_override.changed

- name: Start and enable docker service
  service:
    name: docker
    enabled: True
    state: started
