---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint

platforms:
  - name: instance
    box: bento/ubuntu-18.04
    config_options:
      synced_folder: false
    #provider_raw_config_args:
    #  - "customize ['createhd', '--filename', '${MOLECULE_EPHEMERAL_DIRECTORY:-/tmp}/extra.vdi', '--size', 2 * 1024]"
    #  - "customize ['storagectl', :id, '--name', 'SATA', '--add', 'sata', '--portcount', 2 ]"
    #  - "customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', '${MOLECULE_EPHEMERAL_DIRECTORY:-/tmp}/extra.vdi']"

provisioner:
  name: ansible
  options:
    become: true
  lint:
    name: ansible-lint
  inventory:
    group_vars: 
      all:
        docker_ce_enable: True
        docker_so_packages_add:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        docker_so_packages_del:
          - python-requests
        docker_lvm_storage_enable: False 
        docker_lvm_storage_pv_devices:
          - /dev/sdb
        docker_lvm_storage_lv_size: '1.5G'

        docker_pip_enable: False
        docker_pip_enable_install_script: True
        docker_pip_so_packages:
          - python-devel
          - "@Development tools"
        docker_pip_python_packages:
          - docker-compose

        docker_daemon_config:
          storage-driver: overlay2
          debug: true
          exec-opts:
            - native.cgroupdriver=systemd
          bip: "192.168.200.1/24"
          userland-proxy: true
          live-restore: true
          icc: true
          selinux-enabled: true

verifier:
  name: testinfra
  lint:
    name: flake8
