---

- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    validate_certs: True

- apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
